module.exports =  [
  {
    id: '1',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 11.710,
    weight: '11.710 g',
    images: ['/images/products/bangles/bangles_1.webp'],
    image: '/images/products/bangles/bangles_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '2',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.130,
    weight: '4.130 g',
    images: ['/images/products/bangles/bangles_2.webp'],
    image: '/images/products/bangles/bangles_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '3',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 3.160,
    weight: '3.160 g',
    images: ['/images/products/bangles/bangles_3.webp'],
    image: '/images/products/bangles/bangles_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '4',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 3.100,
    weight: '3.100 g',
    images: ['/images/products/bangles/bangles_4.webp'],
    image: '/images/products/bangles/bangles_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '5',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 7.120,
    weight: '7.120 g',
    images: ['/images/products/bangles/bangles_5.webp'],
    image: '/images/products/bangles/bangles_5.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '6',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.810,
    weight: '5.810 g',
    images: ['/images/products/sakha/sakha_1.webp'],
    image: '/images/products/sakha/sakha_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '7',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.510,
    weight: '5.510 g',
    images: ['/images/products/sakha/sakha_2.webp'],
    image: '/images/products/sakha/sakha_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '8',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.980,
    weight: '4.980 g',
    images: ['/images/products/sakha/sakha_3.webp'],
    image: '/images/products/sakha/sakha_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '9',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 3.330,
    weight: '3.330 g',
    images: ['/images/products/sakha/sakha_4.webp'],
    image: '/images/products/sakha/sakha_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '10',
    name: '',
    category: 'BANGLES-BRACELETS',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.480,
    weight: '4.480 g',
    images: ['/images/products/sakha/sakha_5.webp'],
    image: '/images/products/sakha/sakha_5.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '11',
    name: '',
    category: 'Earrings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.60,
    weight: '5.60 g',
    images: ['/images/products/earrings/earring_1.webp'],
    image: '/images/products/earrings/earring_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '12',
    name: '',
    category: 'Earrings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.640,
    weight: '4.640 g',
    images: ['/images/products/earrings/earring_2.webp'],
    image: '/images/products/earrings/earring_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '13',
    name: '',
    category: 'Earrings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 1.9,
    weight: '1.9 g',
    images: ['/images/products/earrings/earring_3.webp'],
    image: '/images/products/earrings/earring_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '14',
    name: '',
    category: 'Earrings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.85,
    weight: '5.85 g',
    images: ['/images/products/earrings/earring_4.webp'],
    image: '/images/products/earrings/earring_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '15',
    name: '',
    category: 'Earrings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.180,
    weight: '4.180 g',
    images: ['/images/products/earrings/earring_5.webp'],
    image: '/images/products/earrings/earring_5.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '16',
    name: '',
    category: 'chains',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 6.470,
    weight: '6.470 g',
    images: ['/images/products/chains/chain_1.webp'],
    image: '/images/products/chains/chain_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '17',
    name: '',
    category: 'chains',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 14.410,
    weight: '14.410 g',
    images: ['/images/products/chains/chain_2.webp'],
    image: '/images/products/chains/chain_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '18',
    name: '',
    category: 'chains',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 8.620,
    weight: '8.620 g',
    images: ['/images/products/chains/chain_3.webp'],
    image: '/images/products/chains/chain_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '19',
    name: '',
    category: 'chains',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 25.090,
    weight: '25.090 g',
    images: ['/images/products/chains/chain_4.webp'],
    image: '/images/products/chains/chain_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  // {
  //   id: '20',
  //   name: '',
  //   category: 'chains',
  //   metalType: 'Gold',
  //   priceVal: 0,
  //   price: '',
  //   description: '',
  //   purity: '22 Karat Gold (916 Purity)',
  //   weightVal: 14,
  //   weight: '14 g',
  //   images: ['/images/products/chains/chain_5.webp'],
  //   image: '/images/products/chains/chain_5.webp',
  //   hallmarked: true,
  //   sku: '',
  //   certifications: 'BIS Hallmarked & HUID Compliant',
  //   features: ['', '', '', '100% certified hallmarked purity']
  // },
  {
    id: '21',
    name: '',
    category: 'mangalsutra',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.210,
    weight: '4.210 g',
    images: ['/images/products/mangalsutras/mangalsutra_1.webp'],
    image: '/images/products/mangalsutras/mangalsutra_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '22',
    name: '',
    category: 'mangalsutra',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 6.71,
    weight: '6.71 g',
    images: ['/images/products/mangalsutra_2.webp'],
    image: '/images/products/mangalsutra_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '23',
    name: '',
    category: 'mangalsutra',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.570,
    weight: '4.570 g',
    images: ['/images/products/mangalsutra_3.webp'],
    image: '/images/products/mangalsutra_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '24',
    name: '',
    category: 'mangalsutra',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.030,
    weight: '5.030 g',
    images: ['/images/products/mangalsutra_4.webp'],
    image: '/images/products/mangalsutra_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '25',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 6.170,
    weight: '6.170 g',
    images: ['/images/products/bangles/bangles_1.webp'],
    image: '/images/products/bangles/bangles_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '26',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 6.010,
    weight: '6.010 g',
    images: ['/images/products/bangles/bangles_2.webp'],
    image: '/images/products/bangles/bangles_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '27',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.870,
    weight: '5.870 g',
    images: ['/images/products/bangles/bangles_3.webp'],
    image: '/images/products/bangles/bangles_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '28',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 9.450,
    weight: '9.450 g',
    images: ['/images/products/bangles/bangles_4.webp'],
    image: '/images/products/bangles/bangles_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '29',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.940,
    weight: '5.940 g',
    images: ['/images/products/bangles/bangles_5.webp'],
    image: '/images/products/bangles/bangles_5.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '30',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 18.530,
    weight: '18.530 g',
    images: ['/images/products/bracelets/bracelet_6.webp'],
    image: '/images/products/bracelets/bracelet_6.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '31',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 9.080,
    weight: '9.080 g',
    images: ['/images/products/bracelets/bracelet_7.webp'],
    image: '/images/products/bracelets/bracelet_7.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '32',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 8.770,
    weight: '8.770 g',
    images: ['/images/products/bracelets/bracelet_8.webp'],
    image: '/images/products/bracelets/bracelet_8.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '33',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 11.890,
    weight: '11.890 g',
    images: ['/images/products/bracelets/bracelet_9.webp'],
    image: '/images/products/bracelets/bracelet_9.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '34',
    name: '',
    category: 'bangles-bracelets',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.840,
    weight: '5.840 g',
    images: ['/images/products/bracelets/bracelet_10.webp'],
    image: '/images/products/bracelets/bracelet_10.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '35',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 3.790,
    weight: '3.790 g',
    images: ['/images/products/rings/ring_1.webp'],
    image: '/images/products/rings/ring_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '36',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 2.260,
    weight: '2.260 g',
    images: ['/images/products/rings/ring_2.webp'],
    image: '/images/products/rings/ring_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '37',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.610,
    weight: '4.610 g',
    images: ['/images/products/rings/ring_3.webp'],
    image: '/images/products/rings/ring_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '38',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 1.690,
    weight: '1.690 g',
    images: ['/images/products/rings/ring_4.webp'],
    image: '/images/products/rings/ring_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '39',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 2.590,
    weight: '2.590 g',
    images: ['/images/products/rings/ring_5.webp'],
    image: '/images/products/rings/ring_5.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '40',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 5.260,
    weight: '5.260 g',
    images: ['/images/products/rings/ring_6.webp'],
    image: '/images/products/rings/ring_6.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '41',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 6.170,
    weight: '6.170 g',
    images: ['/images/products/rings/ring_7.webp'],
    image: '/images/products/rings/ring_7.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '42',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 4.520,
    weight: '4.520 g',
    images: ['/images/products/rings/ring_8.webp'],
    image: '/images/products/rings/ring_8.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '43',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 1.820,
    weight: '1.820 g',
    images: ['/images/products/rings/ring_9.webp'],
    image: '/images/products/rings/ring_9.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '44',
    name: '',
    category: 'rings',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 1.820,
    weight: '1.820 g',
    images: ['/images/products/rings/ring_9.webp'],
    image: '/images/products/rings/ring_9.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '45',
    name: '',
    category: 'necklaces',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 6.740,
    weight: '6.740 g',
    images: ['/images/products/necklaces/necklace_1.webp'],
    image: '/images/products/necklaces/necklace_1.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '46',
    name: '',
    category: 'necklaces',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 8.020,
    weight: '8.020 g',
    images: ['/images/products/necklaces/necklace_2.webp'],
    image: '/images/products/necklaces/necklace_2.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '47',
    name: '',
    category: 'necklaces',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 3.630,
    weight: '3.630 g',
    images: ['/images/products/necklaces/necklace_3.webp'],
    image: '/images/products/necklaces/necklace_3.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '48',
    name: '',
    category: 'necklaces',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 14.9,
    weight: '14.9 g',
    images: ['/images/products/necklaces/necklace_4.webp'],
    image: '/images/products/necklaces/necklace_4.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '49',
    name: '',
    category: 'necklaces',
    metalType: 'Gold',
    priceVal: 0,
    price: '',
    description: '',
    purity: '22 Karat Gold (916 Purity)',
    weightVal: 14.830,
    weight: '14.830 g',
    images: ['/images/products/necklaces/necklace_5.webp'],
    image: '/images/products/necklaces/necklace_5.webp',
    hallmarked: true,
    sku: '',
    certifications: 'BIS Hallmarked & HUID Compliant',
    features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '50',
    name: '',
    category: 'necklaces',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/necklaces/necklace_6.webp'],
    image: '/images/products/necklaces/necklace_6.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '51',
    name: '',
    category: 'necklaces',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/necklaces/necklace_7.webp'],
    image: '/images/products/necklaces/necklace_7.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '52',
    name: '',
    category: 'necklaces',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/necklaces/necklace_8.webp'],
    image: '/images/products/necklaces/necklace_8.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '53',
    name: '',
    category: 'bangles',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bangles/bangles_6.webp'],
    image: '/images/products/bangles/bangles_6.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '54',
    name: '',
    category: 'bangles',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bangles/bangles_7.webp'],
    image: '/images/products/bangles/bangles_7.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '55',
    name: '',
    category: 'bracelets',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bracelets/bracelet_11.webp'],
    image: '/images/products/bracelets/bracelet_11.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '56',
    name: '',
    category: 'bangles',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bracelets/bracelet_12.webp'],
    image: '/images/products/bracelets/bracelet_12.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '57',
    name: '',
    category: 'bracelets',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bracelets/bracelet_13.webp'],
    image: '/images/products/bracelets/bracelet_13.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '58',
    name: '',
    category: 'bracelets',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bracelets/bracelet_14.webp'],
    image: '/images/products/bracelets/bracelet_14.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '59',
    name: '',
    category: 'bracelets',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bracelets/bracelet_15.webp'],
    image: '/images/products/bracelets/bracelet_15.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '60',
    name: '',
    category: 'bracelets',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bracelets/bracelet_16.webp'],
    image: '/images/products/bracelets/bracelet_16.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '61',
    name: '',
    category: 'bracelets',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/bracelets/bracelet_17.webp'],
    image: '/images/products/bracelets/bracelet_17.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '62',
    name: '',
    category: 'chains',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/chains/chain_5.webp'],
    image: '/images/products/chains/chain_5.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '63',
    name: '',
    category: 'chains',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/chains/chain_6.webp'],
    image: '/images/products/chains/chain_6.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '64',
    name: '',
    category: 'necklaces',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/necklaces/necklace_6.webp'],
    image: '/images/products/necklaces/necklace_6.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '65',
    name: '',
    category: 'necklaces',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/necklaces/necklace_7.webp'],
    image: '/images/products/necklaces/necklace_7.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '66',
    name: '',
    category: 'necklaces',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/necklaces/necklace_8.webp'],
    image: '/images/products/necklaces/necklace_8.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '67',
    name: '',
    category: 'rings',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/rings/ring_10.webp'],
    image: '/images/products/rings/ring_10.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '68',
    name: '',
    category: 'rings',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/rings/ring_11.webp'],
    image: '/images/products/rings/ring_11.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
  {
    id: '69',
    name: '',
    category: 'rings',
    metalType: 'Silver',
    priceVal: 0,
    price: '',
    description: '',
    purity: '925 Silver (925 Purity)',
    // weightVal: 14.830,
    // weight: '14.830 g',
    images: ['/images/products/rings/ring_12.webp'],
    image: '/images/products/rings/ring_12.webp',
    // hallmarked: true,
    sku: '',
    // certifications: 'BIS Hallmarked & HUID Compliant',
    // features: ['', '', '', '100% certified hallmarked purity']
  },
];
